name: firebase_bloc_login
description: OTP Login App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Google
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.7

  # Local Storage
  shared_preferences: ^2.0.15

  # Sign In
  sign_in_with_apple: ^4.2.0
  # google_sign_in: ^5.4.2

  # State
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  meta: ^1.8.0
  
  # UI 
  cupertino_icons: ^1.0.2
  pinput: ^2.2.16
  easy_localization: ^3.0.1

  # Media
  image_picker: ^0.8.6
  grock: ^0.0.9+6
  firebase_messaging: ^14.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
